create table if not exists IPCountryMap(

	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	createdDate datetime not null,
	modifiedDate datetime not null,
	
	ipAddress varchar(45) NOT NULL UNIQUE,
	countryCode varchar(2) NOT NULL,
	
	version bigint not null,
	
  PRIMARY KEY (id)
);

create index IPCountryMap_ipAddress on IPCountryMap (ipAddress);


create table if not exists Question(

	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	createdDate datetime not null,
	modifiedDate datetime not null,
	
	ipAddress varchar(45) NOT NULL,
	question CLOB NOT NULL,
	questionHash varchar(500) NOT NULL,
	countryCode varchar(2) NOT NULL,
	
	version bigint not null,
	
  PRIMARY KEY (id)
);

create index Question_ipAddress_questionHash_createdDate on Question (ipAddress, questionHash, createdDate);
create index Question_countryCode_createdDate on Question (countryCode, createdDate);
create index Question_countryCode on Question (countryCode);

create table if not exists WordBlackList(

	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	createdDate datetime not null,
	modifiedDate datetime not null,
	
	word varchar(255) NOT NULL UNIQUE,
	
	version bigint not null,
	
  PRIMARY KEY (id)
)

